# Нельзя задать уровни ошибок через env
# https://github.com/symfony/monolog-bundle/issues/220
# https://github.com/symfony/monolog-bundle/pull/245

parameters:
  monolog_defaults_max_files: 10
  monolog_defaults_rotation_date_format: 'Y_m_d'

monolog:
  handlers:
    stderr:
      type: stream
      path: 'php://stderr'
      nested: true
      level: debug # В stderr пишем все логи
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine', '!console']
