old_sound_rabbit_mq:
    connections:
        default:
            host:     '%env(RABBITMQ_HOST)%'
            port:     '%env(RABBITMQ_PORT)%'
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost:    '%env(RABBITMQ_VHOST)%'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            #Использование сокета быстрее, но он не работает из-за бага "Error reading data. Received 0 instead of expected 7 bytes"
            #See https://github.com/php-amqplib/php-amqplib/issues/72
            #See https://github.com/php-amqplib/RabbitMqBundle/issues/447
            use_socket: false

    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        example_producer:
            connection:       default
            exchange_options: { name: 'example', type: direct }
            queue_options:    { name: 'example'}