monolog:
  channels: ['api', 'app', 'kafka', 'csv', 'sap', 'poslog']
  handlers:
        fluentd:
          type: stream
          level: info
          path: 'php://stdout'
          formatter: 'monolog.formatter.json'
          channels : ['api', 'app', 'kafka', 'csv', 'sap', 'poslog']
