openapi: 3.0.3

info:
  title: Микросервис
  description: Микросервис создает пользователя
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

paths:
  /api/v1/health/test:
    get:
      summary: Проверка жизнеспособности сервиса
      operationId: CheckService_CheckHealth
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref:  '#/components/schemas/user_service_v1HealthResponse'
      tags:
        - CheckService
  /api/v1/users/create:
    post:
      summary: Создание пользователя
      operationId: Userservice_createuser
      requestBody:
        description: Создание пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_service_v1Create'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_service_v1Success'
      tags:
        - Userservice
components:
  schemas:
    user_service_v1Create:
      type: object
      description: A JSON object containing information
      required: true
      properties:
        userFirstName:
          type: string
        userLastName:
          type: string
        userEmail:
          type: string
        phone:
          type: string
    user_service_v1Success:
      type: object
      properties:
        userId:
          type: integer
    user_service_v1HealthResponse:
      type: object
      properties:
        status:
          type: string
      title: Объект с информацией о работоспособности сервиса
